### ISSUE TITLE
java.sql.SQLException: Can''t call commit when autocommit=true

### ISSUE THREAD

**Issue by Magi1053** [prism/Prism#142]
This error is constantly spamming in the console
```
java.sql.SQLException: Can''t call commit when autocommit=true
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:67)
	at com.mysql.cj.jdbc.ConnectionImpl.commit(ConnectionImpl.java:793)
	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:362)
	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
	at com.helion3.prism.storage.mysql.MySQLRecords.writeExtraData(MySQLRecords.java:143)
	at com.helion3.prism.storage.mysql.MySQLRecords.write(MySQLRecords.java:123)
	at com.helion3.prism.queues.RecordingQueueManager.run(RecordingQueueManager.java:50)
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Solution
- Applicable for MySQL only: Add &relaxAutoCommit=true to the end of your JDBC connection string / URL.

**Example:**
`jdbc:mysql://localhost/prism?autoReconnect=true&relaxAutoCommit=true`

**Comment by LXGaming** [comment]
What version of MySQL are you running?

**Comment by Magi1053** [comment]
MariaDB 1:10.3.14+maria~bionic

**Comment by Magi1053** [comment]
Is this being looked into?
