### ISSUE TITLE
Can not connect to MySQL database

### ISSUE THREAD

**Issue by Mahtaran** [prism/Prism#155]
I hope this is the correct place. I know that for the newer Bukkit versions Prism is maintained [here](https://github.com/AddstarMC/Prism-Bukkit), but since this is about an older version I thought it best to post it here.

When starting my server, I get a big fat stacktrace saying that Prism can not connect to the MySQL database. However, the configuration values are correct, and if I execute `mysql --host=<hostname> --port=<port> --user=<username> --password='<password>' <database>` on the same host (stuff between \<brackets\> replaced with the values in the configuration), I can connect just fine. I think this might be due to my password containing characters which should be escaped in YAML (such as `!`). However, when I try to but 'quotes' around my password and start the server, the YAML config file is rewritten by Prism and the quotes are gone. Any way I can fix this?

Note: I am using Prism 2.0.4 since we are bound to 1.7.10 due to a certain mod (we are using Thermos).

The stack trace:
> [13:47:09 ERROR]: Unable to create initial connections of pool.
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[Util.class:?]
at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116) ~[SQLError.class:?]
at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:343) ~[MysqlIO.class:?]
at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334) ~[ConnectionImpl.class:?]
at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371) ~[ConnectionImpl.class:?]
at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163) ~[ConnectionImpl.class:?]
at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794) ~[ConnectionImpl.class:?]
at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[JDBC4Connection.class:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[Util.class:?]
at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378) ~[ConnectionImpl.class:?]
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305) ~[NonRegisteringDriver.class:?]
at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:278) ~[prism-2.0.4.jar:?]
at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182) ~[prism-2.0.4.jar:?]
at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:701) ~[prism-2.0.4.jar:?]
at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:635) ~[prism-2.0.4.jar:?]
at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:486) [prism-2.0.4.jar:?]
at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:144) [prism-2.0.4.jar:?]
at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:116) [prism-2.0.4.jar:?]
at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:103) [prism-2.0.4.jar:?]
at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:127) [prism-2.0.4.jar:?]
at me.botsko.prism.Prism.dbc(Prism.java:361) [prism-2.0.4.jar:?]
at me.botsko.prism.Prism.onEnable(Prism.java:146) [prism-2.0.4.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [JavaPlugin.class:1.7.10-1614.58]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_242]
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_242]
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_242]
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_242]
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_242]
at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_242]
at java.net.Socket.connect(Socket.java:556) ~[?:1.8.0_242]
at java.net.Socket.<init>(Socket.java:452) ~[?:1.8.0_242]
at java.net.Socket.<init>(Socket.java:262) ~[?:1.8.0_242]
at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254) ~[StandardSocketFactory.class:?]
at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292) ~[MysqlIO.class:?]
... 34 more
> [13:47:09 INFO]: [Prism]: Database connection failed. Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
> [13:47:09 WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
> [13:47:09 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> [13:47:09 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> [13:47:09 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> [13:47:09 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> [13:47:09 WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
> [13:47:09 WARN]: at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
> [13:47:09 WARN]: at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:343)
> [13:47:09 WARN]: at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334)
> [13:47:09 WARN]: at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
> [13:47:09 WARN]: at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
> [13:47:09 WARN]: at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
> [13:47:09 WARN]: at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
> [13:47:09 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> [13:47:09 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> [13:47:09 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> [13:47:09 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> [13:47:09 WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
> [13:47:09 WARN]: at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
> [13:47:09 WARN]: at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
> [13:47:09 WARN]: at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:278)
> [13:47:09 WARN]: at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182)
> [13:47:09 WARN]: at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:701)
> [13:47:09 WARN]: at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:635)
> [13:47:09 WARN]: at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:486)
> [13:47:09 WARN]: at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:144)
> [13:47:09 WARN]: at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:116)
> [13:47:09 WARN]: at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:103)
> [13:47:09 WARN]: at com.helion3.prism.libs.org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:127)
> [13:47:09 WARN]: at me.botsko.prism.Prism.dbc(Prism.java:361)
> [13:47:09 WARN]: at me.botsko.prism.Prism.onEnable(Prism.java:146)
> [13:47:09 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
> [13:47:09 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
> [13:47:09 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
> [13:47:09 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
> [13:47:09 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
> [13:47:09 WARN]: at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
> [13:47:09 WARN]: at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
> [13:47:09 WARN]: at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
> [13:47:09 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
> [13:47:09 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
> [13:47:09 WARN]: at java.lang.Thread.run(Thread.java:748)
> [13:47:09 WARN]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
> [13:47:09 WARN]: at java.net.PlainSocketImpl.socketConnect(Native Method)
> [13:47:09 WARN]: at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> [13:47:09 WARN]: at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> [13:47:09 WARN]: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> [13:47:09 WARN]: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> [13:47:09 WARN]: at java.net.Socket.connect(Socket.java:607)
> [13:47:09 WARN]: at java.net.Socket.connect(Socket.java:556)
> [13:47:09 WARN]: at java.net.Socket.<init>(Socket.java:452)
> [13:47:09 WARN]: at java.net.Socket.<init>(Socket.java:262)
> [13:47:09 WARN]: at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254)
> [13:47:09 WARN]: at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292)
> [13:47:09 WARN]: ... 34 more
> [13:47:09 INFO]: [Prism]: --------------------- ## Important ## ---------------------
> [13:47:09 INFO]: [Prism]: Prism will disable itself because it couldn't connect to a database.
> [13:47:09 INFO]: [Prism]: If you're using MySQL, check your config. Be sure MySQL is running.
> [13:47:09 INFO]: [Prism]: For help - try http://discover-prism.com/wiki/view/troubleshooting/
> [13:47:09 INFO]: [Prism]: --------------------- ## ========= ## ---------------------

**Comment by viveleroi** [comment]
This repository is actually only for the Sponge version of Prism. The bukkit versions are maintained by Addstar, but I don't know that they're able to help with prior versions. We certainly aren't anymore, as we haven't touched it in six years. You can try updating or asking for help in their discord.

**Comment by Mahtaran** [comment]
Ah, my bad. Thanks for the quick response anyway
