### ISSUE TITLE
rollback/restore broken in Sponge API 5.0.

### ISSUE THREAD

**Issue by cartman-2000** [prism/Prism#38]
Neither the rollback or restore work with the newer builds of MC.

[18:16:08] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-05d0adc
    SpongeForge: 1.10.2-2002-5.0.0-BETA-1533
    Minecraft Forge: 12.18.0.2005

For a restore, but the same type of error happens for rollback of blocks and entities.
```
[17:55:33] [Server thread/INFO] [io.github.hsyyid.essentialcmds/]: [cartman2000] executed command pr rs r:20
[17:55:33] [Server thread/DEBUG] [prism/]: MySQL Query: SELECT *, HEX(Player) AS PlayerHexed, HEX(WorldUuid) AS WorldUuidHexed FROM prism_records LEFT JOIN prism_extra ON prism_records.id = prism_extra.record_id WHERE (WorldUuid = UNHEX('4623c8605cac428e8e02976342a08677') AND X > -166 AND X < -126 AND Y > 43 AND Y < 83 AND Z > 152 AND Z < 192 ) AND (Created >= 1467334533 ) AND (WorldUuid = UNHEX('4623c8605cac428e8e02976342a08677') AND X > -166 AND X < -126 AND Y > 43 AND Y < 83 AND Z > 152 AND Z < 192 ) AND (Created >= 1467334533 ) ORDER BY created, y, x, z
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: org.spongepowered.api.data.persistence.InvalidDataException: Could not deserialize something correctly, likely due to bad type data.
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:88)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at com.helion3.prism.api.records.BlockResult.restore(BlockResult.java:135)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at com.helion3.prism.commands.ApplierCommand.lambda$null$0(ApplierCommand.java:88)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at java.util.concurrent.CompletableFuture.uniAcceptStage(Unknown Source)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at java.util.concurrent.CompletableFuture.thenAccept(Unknown Source)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at com.helion3.prism.commands.ApplierCommand.lambda$null$1(ApplierCommand.java:75)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at java.util.concurrent.CompletableFuture.uniAcceptStage(Unknown Source)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at java.util.concurrent.CompletableFuture.thenAccept(Unknown Source)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at com.helion3.prism.commands.ApplierCommand.lambda$getCommand$2(ApplierCommand.java:68)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:179)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:332)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:264)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:82)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:119)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:45)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[17:55:33] [Server thread/INFO] [STDERR/]: [com.helion3.prism.commands.ApplierCommand:lambda$null$0:93]: 	at java.lang.Thread.run(Unknown Source)
[17:55:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.IllegalArgumentException: Invalid UUID string: MemoryDataView{path=WorldUuid, map={UuidLeast=-8213836317794990473, UuidMost=5054103523037037198}}
[17:55:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.UUID.fromString(Unknown Source)
[17:55:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.common.block.SpongeBlockSnapshotBuilder.buildContent(SpongeBlockSnapshotBuilder.java:225)
[17:55:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:86)
[17:55:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 30 more
```

**Comment by cartman-2000** [comment]
This pr should fix the issue.
https://github.com/prism/Prism/pull/39

**Comment by LucidTheStick** [comment]
Is this confirmed working?  I don't get the error and it appears to be trying to work by Querying for changes, but nothing actually happens.  Using MySQL DB and will be trying with debug tonight to track where it get's stuck at.

**Comment by viveleroi** [comment]
I tested it recently with H2 and it seemed to work fine, but I haven't tried MySQL yet, which someone else has reported an NPE issue with.

**Comment by cartman-2000** [comment]
I'm using MySQL 5.5 on my server, and it's working fine for me there.

**Comment by cartman-2000** [comment]
Looks like I spoke too soon before, it looks an api update broke the rollback and restore again. I've been able to get it working on my server with the newest versions of API5.

It would appear that this commit would have broken it.
https://github.com/SpongePowered/SpongeAPI/commit/07d6a0a0ab635e46e2e9d5467cc43c1dc244bf0a

The PR. I still haven't seen any instance of the NRE from #43 on my server, so that one isn't covered in the PR.
#44

**Comment by viveleroi** [comment]
Closing this since the related PR/issues have been merged. If there's any specific issues not covered by an open PR, we can file those separately.
