### ISSUE TITLE
Can't connect with database

### ISSUE THREAD

**Issue by Eufranio** [prism/Prism#40]
I think my plugin is not connecting with the database. Every time i use /prism i and scan a block, i get this message in the console:

[Prism]: Database connection error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'franiprism.prism_data.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
[01:27:44 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'franiprism.prism_data.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
[01:27:44 WARN]:        at sun.reflect.GeneratedConstructorAccessor480.newInstance(Unknown Source)
[01:27:44 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:27:44 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[01:27:44 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[01:27:44 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[01:27:44 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[01:27:44 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[01:27:44 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[01:27:44 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[01:27:44 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[01:27:44 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[01:27:44 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[01:27:44 WARN]:        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
[01:27:44 WARN]:        at me.botsko.prism.actionlibs.ActionsQuery.lookup(ActionsQuery.java:113)
[01:27:44 WARN]:        at me.botsko.prism.wands.InspectorWand$1.run(InspectorWand.java:106)
[01:27:44 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[01:27:44 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[01:27:44 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[01:27:44 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[01:27:44 WARN]:        at java.lang.Thread.run(Thread.java:745)

franiprism is my database.

**Comment by viveleroi** [comment]
Try disabling `sql_mode=only_full_group_by`.

Prism for Bukkit/Spigot is no longer supported and is actually a different repo,  https://github.com/prism/Prism-Bukkit.

**Comment by Eufranio** [comment]
I can't find sql_mode=only_full_group_by :/

**Comment by Eufranio** [comment]
pls help me

**Comment by rlemish** [comment]
http://craftcms.stackexchange.com/questions/12084/getting-this-sql-error-group-by-incompatible-with-sql-mode-only-full-group-by/12845
