### ISSUE TITLE
Prism database error

### ISSUE THREAD

**Issue by Eufranio** [prism/Prism#52]
```
[23:55:57 INFO]: [Prism]: Prism database error. We have to bail in the middle of building primary bulk insert query.
[23:55:57 WARN]: Exception in thread "Craft Scheduler Thread - 79"
[23:55:57 WARN]: org.apache.commons.lang.UnhandledException: Plugin Prism v2.0.6-${env.BUILD_NUMBER} generated an exception while executing task 9910
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1433)
        at me.botsko.prism.actionlibs.RecordingTask.insertActionsIntoDatabase(RecordingTask.java:243)
        at me.botsko.prism.actionlibs.RecordingTask.save(RecordingTask.java:36)
        at me.botsko.prism.actionlibs.RecordingTask.run(RecordingTask.java:352)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

```
I don't know what is the cause, but it is spamming sometimes

**Comment by Eufranio** [comment]
Another random error:
```
[00:01:23 INFO]: [Prism]: Database connection error: Cannot add or update a child row: a foreign key constraint fails (`Prism`.`prism_data_extra`, CONSTRAINT `prism_data_extra_ibfk_1` FOREIGN KEY (`data_id`) REFERENCES `prism_data` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)
[00:01:23 WARN]: java.sql.BatchUpdateException: Cannot add or update a child row: a foreign key constraint fails (`Prism`.`prism_data_extra`, CONSTRAINT `prism_data_extra_ibfk_1` FOREIGN KEY (`data_id`) REFERENCES `prism_data` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)
[00:01:23 WARN]:        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:2018)
[00:01:23 WARN]:        at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1449)
[00:01:23 WARN]:        at me.botsko.prism.actionlibs.RecordingTask.insertExtraData(RecordingTask.java:322)
[00:01:23 WARN]:        at me.botsko.prism.actionlibs.RecordingTask.insertActionsIntoDatabase(RecordingTask.java:256)
[00:01:23 WARN]:        at me.botsko.prism.actionlibs.RecordingTask.save(RecordingTask.java:36)
[00:01:23 WARN]:        at me.botsko.prism.actionlibs.RecordingTask.run(RecordingTask.java:352)
[00:01:23 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[00:01:23 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[00:01:23 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[00:01:23 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[00:01:23 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by viveleroi** [comment]
The second error was likely caused by the first but [Prism for Bukkit](https://github.com/prism/Prism-Bukkit) hasn't been supported since Bukkit ended two years ago.

**Comment by Eufranio** [comment]
Then, there is no fix?

**Comment by viveleroi** [comment]
It's practically impossible to determine what led to this error to begin with but no, there is no fix. Prism for bukkit is not maintained outside PRs.

**Comment by Eufranio** [comment]
Is there a Prism-Spigot or so? I really love Prism because it's the better logger for MC :/

**Comment by viveleroi** [comment]
Spigot is just a bukkit fork and I've decided not to endorse it.

**Comment by Eufranio** [comment]
Okay, thank you.

**Comment by Eufranio** [comment]
Is there a version for 1.7.10 Thermos servers?

**Comment by LemADEC** [comment]
Prism Bukkit works just fine with Thermos. Your database schema is messed up, shutdown your save and restart with a fresh DB

**Comment by Eufranio** [comment]
I did. A lot of times. Deleted DB, plugin, tested with a new server, nothing seems to work here :/

**Comment by LemADEC** [comment]
prism 2.0.6 is for MC 1.8

**Comment by Eufranio** [comment]
I'm using the cauldron 1.7.10 version and getting the same errors...

**Comment by LemADEC** [comment]
prism-2.0.4.jar is the right one to use

**Comment by Eufranio** [comment]
I know and I'm using that...
