### ISSUE TITLE
Infinity is not a valid double value as per JSON specification 

### ISSUE THREAD

**Issue by Bebabo10** [prism/Prism#57]
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]: java.lang.IllegalArgumentException: -Infinity is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.google.gson.Gson.checkValidFloatingPoint(Gson.java:296)
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.google.gson.Gson.access$000(Gson.java:97)
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.google.gson.Gson$4.write(Gson.java:288)
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.google.gson.Gson$4.write(Gson.java:274)
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96)
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60)
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.google.gson.Gson.toJson(Gson.java:593)
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.google.gson.Gson.toJsonTree(Gson.java:486)
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.google.gson.Gson.toJsonTree(Gson.java:465)
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.helion3.prism.util.DataUtil.jsonFromDataView(DataUtil.java:152)
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.helion3.prism.util.DataUtil.jsonFromDataView(DataUtil.java:167)
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.helion3.prism.util.DataUtil.jsonFromDataView(DataUtil.java:167)
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.helion3.prism.storage.mysql.MySQLRecords.write(MySQLRecords.java:107)
[12:28:24] [Thread-16/INFO] [STDERR]: [com.helion3.prism.queues.RecordingQueueManager:run:57]:  at com.helion3.prism.queues.RecordingQueueManager.run(RecordingQueueManager.java:54)

**Comment by hunter688** [comment]
same issue with latest spongeforge (build 1856)

**Comment by viveleroi** [comment]
Can you provide any steps to reproduce?

**Comment by Bebabo10** [comment]
every so often it just spams in console

**Comment by hunter688** [comment]
I will try add some debug code to custom build...

**Comment by viveleroi** [comment]
I can easily debug it I just need to know how to cause it. It's likely coming from a specific block type, because I so far I haven't seen the error.

**Comment by cartman-2000** [comment]
@Bebabo10: Do you happen to have any mods on the server that add blocks or add custom data to blocks, it could be something with these that is causing the issue. I've never seen this issue myself on my own server, but I don't really have very many plugins on it that have custom data stored in blocks.
