### ISSUE TITLE
Console spam 1.10.2 NPE

### ISSUE THREAD

**Issue by inklit** [prism/Prism#61]
This issue was opened before, but it was closed and the author of the issue did not mention the solution to the problem.

Using MySQL, nothing was mentioned except for this. The database for prism is empty.

```
[22:50:17] [pool-3-thread-3/INFO] [STDERR]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]: java.lang.NullPointerException
[22:50:17] [pool-3-thread-3/INFO] [STDERR]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]:      at com.helion3.prism.storage.mysql.MySQLStorageAdapter.getConnection(MySQLStorageAdapter.java:61)
[22:50:17] [pool-3-thread-3/INFO] [STDERR]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]:      at com.helion3.prism.storage.mysql.MySQLRecords.query(MySQLRecords.java:161)
[22:50:17] [pool-3-thread-3/INFO] [STDERR]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]:      at com.helion3.prism.util.AsyncUtil.lambda$async$1(AsyncUtil.java:105)
[22:50:17] [pool-3-thread-3/INFO] [STDERR]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]:      at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138)
[22:50:17] [pool-3-thread-3/INFO] [STDERR]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]:      at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177)
[22:50:17] [pool-3-thread-3/INFO] [STDERR]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]:      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:50:17] [pool-3-thread-3/INFO] [STDERR]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]:      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:50:17] [pool-3-thread-3/INFO] [STDERR]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:50:17] [pool-3-thread-3/INFO] [STDERR]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:50:17] [pool-3-thread-3/INFO] [STDERR]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]:      at java.lang.Thread.run(Thread.java:745)
```

**Comment by viveleroi** [comment]
I can't imagine any scenario outside of a failure to connect to the database, which is what I mentioned in the other issue. I'm pretty sure all connection errors will be caught and logged but I can double check. Are you sure there's nothing else in the logs?
