### ISSUE TITLE
Error with inspection tool

### ISSUE THREAD

**Issue by Sir-Will** [prism/Prism#70]
hey,

getting this error trying to use `/pr i` at a specific location
```
[03:03:57] [pool-2-thread-40/INFO] [STDERR/luckperms]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]: java.lang.NullPointerException
[03:03:57] [pool-2-thread-40/INFO] [STDERR/luckperms]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]: 	at java.io.StringReader.<init>(StringReader.java:50)
[03:03:57] [pool-2-thread-40/INFO] [STDERR/luckperms]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]: 	at com.google.gson.JsonParser.parse(JsonParser.java:45)
[03:03:57] [pool-2-thread-40/INFO] [STDERR/luckperms]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]: 	at com.helion3.prism.storage.mysql.MySQLRecords.query(MySQLRecords.java:184)
[03:03:57] [pool-2-thread-40/INFO] [STDERR/luckperms]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]: 	at com.helion3.prism.util.AsyncUtil.lambda$async$1(AsyncUtil.java:105)
[03:03:57] [pool-2-thread-40/INFO] [STDERR/luckperms]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]: 	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138)
[03:03:57] [pool-2-thread-40/INFO] [STDERR/luckperms]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]: 	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183)
[03:03:57] [pool-2-thread-40/INFO] [STDERR/luckperms]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[03:03:57] [pool-2-thread-40/INFO] [STDERR/luckperms]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[03:03:57] [pool-2-thread-40/INFO] [STDERR/luckperms]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[03:03:57] [pool-2-thread-40/INFO] [STDERR/luckperms]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[03:03:57] [pool-2-thread-40/INFO] [STDERR/luckperms]: [com.helion3.prism.util.AsyncUtil:lambda$async$1:120]: 	at java.lang.Thread.run(Thread.java:745)
```

Prism-3.0.0-beta2-27-g9cbbaf2-all

**Comment by viveleroi** [comment]
Does this happen with every use or only for specific records?

**Comment by Sir-Will** [comment]
Only specific records. Tried it at a different location without any issues.

**Comment by viveleroi** [comment]
I've put a simple check in the code to only parse extra data if it's present but without steps to reproduce I can't be sure why it was empty to being with.
