### ISSUE TITLE
Server crashing after importing world

### ISSUE THREAD

**Issue by t2wave** [prism/Prism#89]
So I imported a world a couple times with different plugins just to test, but afterward the server crashes and continues to crash after startup. Here is the crash report.

[crash-2017-03-17_09.46.42-server.txt](https://github.com/prism/Prism/files/851023/crash-2017-03-17_09.46.42-server.txt)

```
java.lang.Error
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1186)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:137)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.loadServerData(AbstractConnectProtocol.java:669)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:402)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:811)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:469)
	at org.mariadb.jdbc.Driver.connect(Driver.java:104)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:105)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
	at com.helion3.prism.storage.mysql.MySQLStorageAdapter.connect(MySQLStorageAdapter.java:73)
	at com.helion3.prism.Prism.onServerStart(Prism.java:143)
	at org.spongepowered.common.event.listener.GameStartedServerEventListener_Prism_onServerStart12.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:308)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:337)
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:553)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:872)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:300)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:444)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by viveleroi** [comment]
Unfortunately I can't reproduce this, and the error is extremely generic. Until we can narrow down the cause, there's nothing we can do. The failure looks like it's occurring in JDBC and isn't something Prism is directly capable of handling.
